import type { CTA, Card, SectionCopy } from "./types";

export const pageContent = { brand: "Bombay Blokes", navigation: "Performance marketing", stickyNote: "Built for brands ready to see the whole picture." };
export const heroContent = { eyebrow: "Performance marketing, without the performance theatre", title: "Your ads are not the problem. The system around them is.", body: "Bombay Blokes helps ambitious brands find the leaks between attention, intent and purchase—then fixes them with creative, conversion and media working as one.", primary: { label: "Find your next growth constraint", href: "#enquiry" }, secondary: { label: "See how the system works", href: "#operating-system" }, trust: "A senior team for founders who have outgrown guesswork.", stats: [{ value: "₹12Cr+", label: "media guided" }, { value: "38", label: "growth sprints" }, { value: "6", label: "disciplines in one room" }], formTitle: "Start with the honest version", formBody: "Tell us where growth feels stuck. We will tell you what we would look at first.", formButton: "Get the growth diagnosis", fields: ["Name", "Company", "Website", "Monthly ad spend", "Phone", "Email", "Biggest growth challenge"] };
export const socialProof = { line: "Good growth leaves evidence.", logos: ["Dancing Leaf", "SCS Sports", "JK Diamonds", "The Feline Foundation", "Supersox"] };
export const reality: SectionCopy = { eyebrow: "The reality", title: "Most agencies optimise the campaign. Your customer experiences a business.", body: "A winning ad can still meet a slow page, vague offer, missing follow-up and a checkout that asks too much. When that happens, media gets blamed for work it was never meant to do alone." };
export const growthKillers: Card[] = [{ title: "Creative fatigue", body: "The same promise, dressed differently, until the market stops noticing." }, { title: "A leaky handoff", body: "Interest arrives on a landing page that does not continue the conversation." }, { title: "False certainty", body: "Reports celebrate platform metrics while contribution margin quietly erodes." }, { title: "Learning debt", body: "Tests are run, but nobody turns their outcomes into a sharper next bet." }];
export const growthKillersCopy: SectionCopy = { eyebrow: "What quietly breaks growth", title: "Four habits that make a good business harder to buy from.", body: "These are rarely a single catastrophic mistake. They are small breaks in the customer journey, repeated long enough to become expensive." };
export const plateau: SectionCopy = { eyebrow: "Why brands plateau", title: "The first ₹10 lakh in revenue is often momentum. The next needs a machine.", body: "Early growth tolerates instinct. At scale, every vague message, untracked signal and missed repeat purchase compounds. The plateau is not a failure of effort; it is the point where your system asks to be rebuilt." };
export const thinkDifferent: SectionCopy = { eyebrow: "A founder’s view", title: "We do not ask how to buy more traffic. We ask what makes the next customer say yes.", body: "That question changes the work. It pulls creative, offer, landing page, measurement and retention into the same conversation—and makes profit the score that matters." };
export const operatingSystem = { eyebrow: "The growth operating system", title: "One weekly rhythm. Fewer opinions. Better decisions.", body: "Every sprint turns customer signals into a clear priority, a set of experiments and a shared view of what changed.", steps: ["Listen to customer and store signals", "Name the constraint worth solving", "Build the creative and conversion response", "Launch, learn and compound"] };
export const framework = { eyebrow: "Performance framework", title: "Growth is a relay, not a channel.", body: "Each link has a job. We improve the handoff instead of asking ads to carry the entire race.", steps: ["Creative", "Landing page", "Tracking", "Ads", "CRO", "Retention", "Repeat purchases", "Profit"] };
export const aiOptimisation = { eyebrow: "AI-powered optimisation", title: "AI widens the field. Humans choose the direction.", body: "We use assisted research and production to explore more credible angles quickly. Judgment still decides what belongs to your brand and what deserves budget.", items: ["Creative testing", "Copy variations", "Audience research", "Landing pages", "Automation", "Reporting", "Journey mapping", "Experiment design"] };
export const founder = { eyebrow: "Founder philosophy", quote: "You do not need more dashboards. You need someone willing to point at the uncomfortable number.", body: "Bombay Blokes was built for teams that value candour over theatre. We share the bad news early, protect the good ideas with evidence and keep the work close to the customer." };
export const creativeExamples = { eyebrow: "Creative examples", title: "A feed is not a billboard. It is a negotiation for attention.", body: "Our creative system gives each idea a role—from interruption to proof to objection handling.", cards: [{ label: "01 / Interrupt", title: "The familiar friction", body: "Name the moment your customer already recognises." }, { label: "02 / Reframe", title: "The better question", body: "Show why their current solution leaves value behind." }, { label: "03 / Prove", title: "The evidence trail", body: "Make the decision feel safer without making the story smaller." }] };
export const caseStudies = { eyebrow: "Selected proof", title: "The work gets more interesting when the business question gets specific.", cases: [{ title: "Dancing Leaf", stat: "+42%", body: "Revenue growth after rebuilding the acquisition-to-checkout journey." }, { title: "SCS Sports", stat: "3.1x", body: "Return from a creative testing system built around real buyer objections." }, { title: "JK Diamonds", stat: "-28%", body: "Lower acquisition cost after aligning high-intent search with richer product proof." }] };
export const caseStudiesCopy: SectionCopy = { eyebrow: caseStudies.eyebrow, title: caseStudies.title, body: "A few of the measurable shifts created when the whole journey is allowed into the room." };
export const metrics = { eyebrow: "The dashboard", title: "The numbers we watch when vanity is not invited.", metrics: [{ label: "Blended efficiency", value: "4.2x" }, { label: "Checkout completion", value: "68%" }, { label: "Repeat revenue", value: "31%" }, { label: "Creative learnings", value: "127" }] };
export const metricsCopy: SectionCopy = { eyebrow: metrics.eyebrow, title: metrics.title, body: "A practical readout for the decisions that actually alter the business." };
export const testimonials = [{ quote: "They did not bring us a prettier report. They found the reason our best ads stopped converting.", name: "Growth lead", company: "D2C lifestyle brand" }, { quote: "The team asks the questions our previous partners skipped. That alone changed the quality of our decisions.", name: "Founder", company: "Consumer health company" }];
export const testimonialsCopy: SectionCopy = { eyebrow: "What clients remember", title: "The work should make your team feel less alone in the hard decisions.", body: "A partner earns trust by being useful when the answer is not immediately obvious." };
export const industries = { eyebrow: "Where the system travels", title: "Different markets. The same demand for clear thinking.", items: ["Healthcare", "Education", "Sports", "Fitness", "Lifestyle", "Premium brands"] };
export const industriesCopy: SectionCopy = { eyebrow: industries.eyebrow, title: industries.title, body: "The patterns change. The need to understand the customer does not." };
export const first90Days = { eyebrow: "Your first 90 days", title: "Enough structure to move quickly. Enough patience to learn properly.", phases: [{ label: "Week 1", body: "Audit the story, signals and economics." }, { label: "Week 2", body: "Prioritise the constraints and measurement plan." }, { label: "Month 1", body: "Launch the first focused experiments." }, { label: "Month 2", body: "Expand what is earning attention and intent." }, { label: "Month 3", body: "Turn repeated learnings into your operating playbook." }] };
export const first90DaysCopy: SectionCopy = { eyebrow: first90Days.eyebrow, title: first90Days.title, body: "The initial engagement is deliberately paced: fast enough to create movement, deliberate enough to build a useful learning loop." };
export const pricing = { eyebrow: "Transparent pricing", title: "A serious growth partner should be clear about the investment.", body: "Performance marketing engagements begin with a dedicated senior team, a defined operating rhythm and work that reaches beyond the ad account.", price: "₹45,000/month", note: "Media spend is separate. Scope follows the business constraint, not a generic retainer.", cta: { label: "Talk through the right scope", href: "#enquiry" } as CTA };
export const pricingCopy: SectionCopy = { eyebrow: pricing.eyebrow, title: pricing.title, body: pricing.body };
export const faq = { eyebrow: "Questions worth asking", title: "Before you hand anyone the keys to your growth.", items: [{ q: "Do you only manage Google and Meta ads?", a: "No. Media is one part of the system. We also work across creative strategy, landing pages, conversion rate optimisation and retention." }, { q: "Are you a Performance Marketing Agency Mumbai brands can meet in person?", a: "Yes. We are based in Mumbai and work closely with teams in India and beyond." }, { q: "Can you work with our internal team?", a: "Yes. We are designed to make internal teams clearer and faster, not dependent." }, { q: "Do you support Google Ads, Meta Ads and Amazon Advertising?", a: "Yes. Channel choice follows customer intent and the commercial question—not a platform preference." }, { q: "What does Shopify CRO involve?", a: "We investigate the choices, proof and friction between a product page and a completed purchase." }, { q: "Do you offer WhatsApp and email marketing?", a: "Where retention is the constraint, we build the lifecycle conversations that earn the next order." }, { q: "When will we see results?", a: "The first learning should appear quickly. Durable improvement needs enough signal to separate luck from a pattern." }, { q: "Can AI replace a growth team?", a: "AI can accelerate research and production. It cannot yet own commercial judgment or understand the nuance of your customer." }, { q: "Do you take every brand on?", a: "No. We look for access, honesty and a team willing to change what the evidence asks them to change." }, { q: "What happens after the first 90 days?", a: "We agree on the next constraint, refine the operating rhythm and continue only where the work is creating useful momentum." }] };
export const cta = { eyebrow: "The next honest conversation", title: "If growth feels noisier than it should, let us find the reason together.", body: "No grand promises. Just a practical first look at the system your next customer will actually experience.", button: { label: "Book the growth diagnosis", href: "#enquiry" } as CTA };

export const googleAdsLanding = {
  hero: { eyebrow: "Performance marketing agency in Mumbai", title: "Google Ads should bring customers not another dashboard to worry about.", body: "Find the leaks between a high-intent search and a completed order. We build Google Ads, landing pages and measurement around the moment your customer decides.", cta: "Get a free account diagnosis", secondary: "See the 90-day plan", trust: "For D2C teams and ambitious businesses ready to make every paid click work harder.", stats: [{ value: "4.2x", label: "blended efficiency" }, { value: "31%", label: "repeat revenue" }, { value: "68%", label: "checkout completion" }], formTitle: "Get your free account diagnosis", formBody: "A senior strategist will review the problem before recommending the work.", formButton: "Request my diagnosis", fields: ["Name", "Email", "Phone", "Website Link"], success: "Thanks—your diagnosis request is on its way to our team.", error: "We could not send your request. Please check your details and try again." },
  proof: { heading: "A Google Ads management agency built for the question behind the click.", items: ["Google Ads experts", "Meta Ads experts", "D2C marketing agency", "Amazon advertising agency"] },
  problem: { eyebrow: "The expensive part nobody shows you", title: "More impressions will not fix a journey that loses intent after the ad.", body: "If your cost per lead climbs while qualified demand is right there, the issue is usually larger than a bid. The message, page, offer and follow-up need to agree.", points: ["Search terms that do not reflect buyer intent", "Landing pages that restart the conversation", "Reports that hide the cost of a low-quality lead"], image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=85" },
  system: { eyebrow: "How we improve performance", title: "One focused growth loop, from query to profit.", body: "This is performance marketing ecommerce teams can actually act on: find the constraint, build a response, measure the signal, then make the next decision clearer.", steps: ["Audit demand and economics", "Sharpen the offer and creative", "Build the conversion path", "Optimise against profit signals"] },
  work: { eyebrow: "What changes when the whole system is visible", title: "Performance marketing services that give paid media somewhere better to send people.", cards: [{ label: "Google advertising agency", title: "Intent-led acquisition", body: "Campaign architecture shaped by commercial intent—not just keyword volume." }, { label: "Conversion layer", title: "Pages that finish the story", body: "Clearer offers, credible proof and fewer reasons to hesitate." }, { label: "Retention layer", title: "A second order is part of the first", body: "Email and WhatsApp journeys that keep a paid customer worth acquiring." }], image: "https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1200&q=85" },
  results: { eyebrow: "What we measure", title: "The numbers that tell you whether growth is becoming healthier.", metrics: [{ value: "4.2x", label: "Blended Efficiency" }, { value: "31%", label: "Repeat Revenue" }, { value: "68%", label: "Checkout Completion" }], quote: "They found why strong ads were sending people into a weak decision journey—and fixed the handoff.", attribution: "Growth lead, D2C lifestyle brand" },
  pricing: { eyebrow: "Clear investment", title: "Serious growth needs a clear starting point.", body: "Performance marketing cost starts at ₹45,000 per month. Scope is built around the constraint we uncover, with media spend kept separate and transparent.", cta: "Talk through your growth constraint", image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=85" },
  faq: { eyebrow: "Questions before you commit", title: "The answers a serious Google Ads partner should be ready to give.", body: "The right performance marketing agency near me will make the work, the investment and the next decision easier to understand.", items: [{ question: "What does a Google Ads management agency actually improve?", answer: "We improve the full path from a high-intent query to a qualified lead or order: campaign structure, creative, landing-page clarity and the measurement behind each decision." }, { question: "Do you work as a Meta Ads expert too?", answer: "Yes. Google captures active intent; Meta can create and nurture demand. We use each channel when it has a clear job in the customer journey." }, { question: "Can you help with CRO and landing pages?", answer: "Yes. Conversion rate optimisation and landing-page work are central to performance marketing ecommerce, especially when paid traffic is arriving but not turning into revenue." }, { question: "What is the performance marketing cost?", answer: "Engagements begin at ₹45,000 per month, with media spend separate. The exact scope follows the constraint we need to solve." }, { question: "Do you work with D2C brands?", answer: "Yes. As a D2C marketing agency, we work on acquisition, conversion and retention so the first order has a better chance of becoming a second." }], cta: "Request the diagnosis", note: "A practical first step toward choosing the best Google Ads agency for the work ahead." }
};
