"use client";

import { motion } from "framer-motion";
import Navbar from "@/app/components/Navbar"
import CountUp from "react-countup";
import { ArrowIcon, CheckIcon } from "./icons";
import { googleAdsLanding as content } from "./data";
import LeadForm from "./LeadForm";
import SmoothScroll from "@/app/components/SmoothScroll";

const reveal = { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.18 }, transition: { duration: 0.55 } };
const Button = ({ children, href = "#enquiry", light = false }: { children: string; href?: string; light?: boolean }) => <a href={href} className={`inline-flex min-h-12 items-center justify-center gap-2 rounded-xl px-5 py-3 text-sm font-semibold transition duration-200 hover:-translate-y-0.5 ${light ? "bg-white text-black" : "bg-[#f7bf36] text-black shadow-[0_12px_32px_rgba(247,191,54,.2)]"}`}>{children}<ArrowIcon size={16} /></a>;
const ImagePanel = ({ src, label }: { src: string; label: string }) => <div className="relative min-h-72 overflow-hidden rounded-[1.75rem] bg-zinc-800 shadow-2xl md:min-h-full"><img src={src} alt={label} className="absolute inset-0 h-full w-full object-cover opacity-85 transition duration-700 hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-transparent" /><p className="absolute bottom-5 left-5 text-xs font-medium uppercase tracking-[.18em] text-white/75">{label}</p></div>;
const MetricValue = ({ value }: { value: string }) => { const match = value.match(/^([\d.]+)(.*)$/); if (!match) return value; const numeric = Number(match[1]); const suffix = match[2]; return <CountUp end={numeric} decimals={match[1].includes(".") ? 1 : 0} suffix={suffix} enableScrollSpy scrollSpyOnce />; };

export default function GoogleAdsLanding() { return <SmoothScroll><main className="overflow-hidden text-black">
  <section className="relative text-black md:pb-24">
    <div className="" />
    <div className="container relative">
      <Navbar/>
      
  
  <div className="lg:mt-26 mt-0 grid items-center gap-10 lg:grid-cols-[1.1fr_.9fr]"><motion.div {...reveal}><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#f7bf36]">{content.hero.eyebrow}</p><h1 className="title mt-5 max-w-3xl text-5xl font-medium leading-[.93] tracking-[-.065em] md:text-7xl">{content.hero.title}</h1><div className="mt-8"><Button>{content.hero.cta}</Button></div><p className="subtitle mt-7 max-w-md text-xs leading-5 text-black/45">{content.hero.trust}</p></motion.div><motion.div {...reveal}><LeadForm /></motion.div></div>
 
  </div></section>
  <section className=" py-20 md:py-28"><div className="container grid gap-10 lg:grid-cols-2"><motion.div {...reveal}><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#bd7b00]">{content.problem.eyebrow}</p><h2 className="heading mt-5 max-w-xl text-4xl font-medium leading-[.98] tracking-[-.055em] md:text-6xl">{content.problem.title}</h2><p className="subtitle mt-6 max-w-xl text-base leading-7 text-black/65">{content.problem.body}</p><ul className="mt-8 space-y-3">{content.problem.points.map((point) => <li className="subtitle flex gap-3 text-sm leading-6" key={point}><CheckIcon className="mt-1 shrink-0 text-[#bd7b00]" size={15} />{point}</li>)}</ul><div className="mt-8"><Button>{content.hero.cta}</Button></div></motion.div><motion.div {...reveal}><ImagePanel src={content.problem.image} label="Every paid click deserves a better next step" /></motion.div></div></section>
  <section id="plan" className="bg-[#151515] py-20 text-white md:py-28"><div className="container"><motion.div {...reveal} className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#f7bf36]">{content.system.eyebrow}</p><h2 className="heading mt-5 text-4xl font-medium leading-[.98] tracking-[-.055em] md:text-6xl">{content.system.title}</h2><p className="subtitle mt-6 max-w-xl text-base leading-7 text-white/60">{content.system.body}</p></motion.div><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{content.system.steps.map((step, index) => <motion.div {...reveal} key={step} className="rounded-2xl border border-white/15 bg-white/5 p-6"><p className="heading text-5xl leading-none text-[#f7bf36]">0{index + 1}</p><p className="heading mt-12 text-lg leading-6">{step}</p></motion.div>)}</div></div></section>
  <section className=" py-20 md:py-28"><div className="container"><motion.div {...reveal} className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#bd7b00]">{content.work.eyebrow}</p><h2 className="heading mt-5 text-4xl font-medium leading-[.98] tracking-[-.055em] md:text-6xl">{content.work.title}</h2><div className="mt-8"><Button>{content.hero.cta}</Button></div></div><ImagePanel src={content.work.image} label="Media, conversion and retention in one conversation" /></motion.div><div className="mt-5 grid gap-3 md:grid-cols-3">{content.work.cards.map((card) => <article key={card.title} className="rounded-2xl bg-[#ebe9e2] p-6 transition hover:-translate-y-1"><p className="text-[11px] font-semibold uppercase tracking-widest text-[#bd7b00]">{card.label}</p><h3 className="heading mt-9 text-2xl tracking-tight">{card.title}</h3><p className="subtitle mt-3 text-sm leading-6 text-black/60">{card.body}</p></article>)}</div></div></section>
  <section className="bg-[#f7bf36]  py-20 md:py-28"><div className="container"><p className="text-xs font-semibold uppercase tracking-[.2em]">{content.results.eyebrow}</p><h2 className="heading mt-5 max-w-4xl text-4xl font-medium leading-[.98] tracking-[-.055em] md:text-6xl">{content.results.title}</h2><div className="mt-12 grid gap-4 md:grid-cols-[1fr_1fr]"><div className="grid grid-cols-3 gap-3">{content.results.metrics.map((metric) => <div key={metric.label} className="rounded-2xl bg-black p-5 text-white"><strong className="text-5xl tracking-tight text-[#f7bf36]"><MetricValue value={metric.value} /></strong><p className="title mt-8  text-white/60">{metric.label}</p></div>)}</div><figure className="rounded-2xl bg-white p-7"><blockquote className="heading text-2xl leading-tight tracking-tight">“{content.results.quote}”</blockquote><figcaption className="subtitle mt-8 text-sm text-black/55">{content.results.attribution}</figcaption></figure></div></div></section>
  <section className=" py-20 md:py-28"><div className="container grid gap-10 lg:grid-cols-2"><motion.div {...reveal}><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#bd7b00]">{content.pricing.eyebrow}</p><h2 className="heading mt-5 text-4xl font-medium leading-[.98] tracking-[-.055em] md:text-6xl">{content.pricing.title}</h2><p className="subtitle mt-6 max-w-xl text-base leading-7 text-black/65">{content.pricing.body}</p><div className="mt-8"><Button>{content.pricing.cta}</Button></div></motion.div><motion.div {...reveal}><ImagePanel src={content.pricing.image} label="Clear scope. Clear next steps." /></motion.div></div></section>
  <section className="bg-[#eae7df] py-20 md:py-28"><div className="container"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#bd7b00]">{content.faq.eyebrow}</p><h2 className="heading mt-5 max-w-4xl text-4xl font-medium leading-[.98] tracking-[-.055em] md:text-6xl">{content.faq.title}</h2><p className="subtitle mt-6 max-w-2xl text-base leading-7 text-black/65">{content.faq.body}</p><div className="mt-10 divide-y divide-black/10 border-y border-black/10">{content.faq.items.map((item) => <details key={item.question} className="group py-5"><summary className="heading flex cursor-pointer list-none items-center justify-between gap-5 text-lg font-medium"><span>{item.question}</span><span className="text-[#bd7b00] group-open:rotate-45">+</span></summary><p className="subtitle max-w-3xl pt-4 text-sm leading-6 text-black/65">{item.answer}</p></details>)}</div></div></section>
  <section className="bg-[#151515] py-20 text-white md:py-28 "><div className="container text-center lg:mb-0 mb-10"><motion.div {...reveal}><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#f7bf36]">{content.faq.eyebrow}</p><h2 className="heading mx-auto mt-5 max-w-4xl text-4xl font-medium leading-[.98] tracking-[-.055em] md:text-6xl">{content.faq.title}</h2><p className="subtitle mx-auto mt-6 max-w-2xl text-base leading-7 text-white/60">{content.faq.note}</p><div className="mt-8"><Button>{content.faq.cta}</Button></div></motion.div></div></section>
</main></SmoothScroll> }
